GET http://localhost:8800/api/hotels
Content-Type: application/json

{

}

###

PUT http://localhost:8800/api/hotels/654188ce2eadc5ade98e0908
Content-Type: application/json

{
    "name": "Hotel Luchianno"
}

###

POST http://localhost:8800/api/hotels
Content-Type: application/json

{
    "name": "Hotel Mariano",
    "type": "hotel",
    "city": "berlin",
    "address": "algunlugar",
    "distance": "300",
    "title": "alto hotel",
    "description": "hotel description",
    "cheapestPrice": 100
}


###


DELETE http://localhost:8800/api/hotels/65416d049de42a7c6d0cbac7


###

POST http://localhost:8800/api/auth/register
Content-Type: application/json

{
    "username": "prueba",
    "email": "prueba@jjs.com",
    "password": "1234"
    
}


###