GET http://localhost:8800/api/hotels
Content-Type: application/json

{

}

###

PUT http://localhost:8800/api/hotels/654188ce2eadc5ade98e0908
Content-Type: application/json

{
    "name": "Hotel Crack Updated"
}

###

POST http://localhost:8800/api/hotels
Content-Type: application/json

{
    "name": "Hotel angeles 4",
    "type": "hotel",
    "city": "london",
    "address": "algunlugar",
    "distance": "300",
    "title": "alto hotel",
    "description": "hotel description",
    "cheapestPrice": 100
}


###


DELETE http://localhost:8800/api/hotels/65416d049de42a7c6d0cbac7


###

POST http://localhost:8800/api/auth/register
Content-Type: application/json

{
    "username": "admin3",
    "email": "admin3@jjs.com",
    "password": "5444",
    "isAdmin": true
    
}


###


POST http://localhost:8800/api/auth/login
Content-Type: application/json

{
    "username": "admin3",
    "password": "5444"
    
}


###


GET  http://localhost:8800/api/users/checkadmin/654419ddc129ccccfda2c36e
Content-Type: application/json

{
    "username": "prueba"
}

###

POST http://localhost:8800/api/rooms/65416e609de42a7c6d0cbac9
Content-Type: application/json

{
    "title": "King Room",
    "description": "King size bed, 1 bathroom",
    "price": 100,
    "maxPeople":2,
    "roomNumbers": [{"number":101}, {"number":102}, {"number":103}]
    
}

###

DELETE http://localhost:8800/api/rooms/65450bf78c1b56a6976c315f/65416e609de42a7c6d0cbac9
Content-Type: application/json


###

GET http://localhost:8800/api/hotels/countByCity?cities=berlin,madrid,london
Content-Type: application/json

{

}

###

